
# Ejercicios

Vamos a seguir trabajando con el *csv* de `rating-and-performance`, pero vamos a añadir un *csv* más para completar la información de nuestro *e-commerce*. En concreto, vamos a incluir: 

- `insights.csv`: Tenemos datos sobre el éxito de vendedores activos. Sus columnas son: 



    | Nombre de columna         | Descripción                                                                                            |
    |---------------------------|--------------------------------------------------------------------------------------------------------|
    | rating                    | La calificación del producto. (Float)                                                                  |
    | listedproducts            | El número de productos listados en la plataforma de comercio electrónico Wish. (Integer)                |
    | totalunitssold            | El número total de unidades vendidas del producto. (Integer)                                           |
    | meanunitssoldperproduct   | El número promedio de unidades vendidas por producto. (Float)                                         |
    | merchantratingscount      | El número de calificaciones para el vendedor. (Integer)                                                |
    | meanproductprices         | El precio promedio del producto. (Float)                                                               |
    | meanretailprices          | El precio minorista promedio del producto. (Float)                                                     |
    | averagediscount           | El descuento promedio aplicado al producto. (Float)                                                    |
    | meandiscount              | El descuento medio aplicado al producto. (Float)                                                       |
    | meanproductratingscount   | El número promedio de calificaciones para el producto. (Float)                                         |
    | totalurgencycount         | El número total de recuentos de urgencia para el producto. (Integer)                                   |
    | urgencytextrate           | La tasa de ofertas de texto de urgencia para el producto. (Float)                                      |



**Los ejercicios que os planteamos son:**

1. Unid los dos DataFrames en uno solo, usando el método que considereis más correcto. Querremos quedarnos con todos los productos que estén en los dos conjuntos de datos. 

2. Explorad el nombre de las columnas, ¿hay alguna que este repetida o que no nos aporte información de valor? ¿Hay alguna columna que solo tenga un valor? En caso de ser así, eliminadlas. **NOTA** Hay tres columnas que cuando exploramos sus valores únicos y sus frecuencias ayer, nos deberíamos haber dado cuenta que solo tiene un valor.  


3. Algunas de las columnas tienen `.` en sus nombres y en otras tenemos `_`.  Unifica el nombre de las columnas para que todas tengan "_". Además, todas deben estar en minúsculas. 

4. En la columna de `merchant_info_subtitle`, si nos fijamos hay algunas celdas donde tenemos entre paréntesis el número total de calificaciones para el comerciante (que es la misma información que la que tenemos en la columna "merchant_rating_count"). Eliminad de la columna "merchant_info_subtitle" la parte del *string* de los paréntesis. Guardar el resultado de vuestra limpieza en una columna que se llame igual, es decir, "merchant_info_subtitle". 


5. Si nos fijamos, en la primera fila antes solo teníamos un paréntesis, pero los hemos eliminado en el paso anterior, y ahora tenemos un *string* vacío, lo cual no tiene mucho sentido. En este ejercicio debereis reemplazar esos *strings* vacios por nulos de Pandas (**NOTA** estos deben ser indicados de la siguiente forma `np.nan`, y deberéis importar numpy). 

6. Hay ciertas columnas que no vamos a necesitar para nuestro análisis. En concreto, vamos a eliminar las columnas de `badges_count`, `product_variation_inventory`, `urgency_text`, `merchant_title`, `merchant_has_profile_picture`, `merchant_profile_picture`, `product_picture`, `total_urgency_count`, `has_urgency_banner` y `urgency_text_rate`. Guardad los cambios realizados hasta este punto en un csv para usarlo en los ejercicios de la lección de mañana. 

7. Pongamos en práctica el filtrado de datos en Pandas: 

    - Seleccionad aquellos productos cuyo color es verde. ¿Cuántos productos tenemos?

    - Seleccionad aquellos productos cuyo color es verde y rojo. ¿Cuántos productos tenemos de cada tipo de color?

    - Seleccionad aquellos productos de la talla M, que valgan más de 15. ¿Cuántos productos tenemos?

    - Seleccionad aquellos productos cuyo precio este entre 1 y 2 (ambos inclusive). ¿Cuántos productos tenemos?

    - Filtrad los datos, para extraer solo aquellos productos que tengan uno o más dígitos en su titulo. ¿Cuántos productos hay?

In [170]:
import pandas as pd
import re
import numpy as np
pd.set_option('display.max_columns', None)

In [171]:
df_i = pd.read_csv('insight.csv')
df_i.head(2)

,index,merchant.id,listed.products,total.units.sold,mean.units.sold.per.product,rating,merchant.ratings.count,mean.product.prices,mean.retail.prices,average.discount,mean.discount,mean.product.ratings.count,total.urgency.count,urgency.text.rate
0,0,5357bcf2bb72c5504882e889,2,120000,60000.0,4.219,320031.0,9.00,20.0,54.0,54.0,8836.0,1.0,50.0
1,1,5708773c3c02161b3f8c7900,5,107100,21420.0,3.934,139223.0,7.76,34.2,61.0,61.0,4010.0,3.0,60.0

In [172]:
df_r = pd.read_csv('rating-and-performance.csv')
df_r.head(2)

,index,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14,EUR,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0,0,0,0,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,50,Livraison standard,4,0,34,50,1.0,Quantité limitée !,CN,zgrdejia,zgrdejia,(568 notes),568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.0,22,EUR,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,0,0,0,0,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,50,Livraison standard,2,0,41,50,1.0,Quantité limitée !,CN,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08

In [173]:
df_mer = pd.merge(df_i, df_r, left_on='merchant.id', right_on='merchant_id', suffixes=('', '_r'))
df_mer.head(2)

,index,merchant.id,listed.products,total.units.sold,mean.units.sold.per.product,rating,merchant.ratings.count,mean.product.prices,mean.retail.prices,average.discount,mean.discount,mean.product.ratings.count,total.urgency.count,urgency.text.rate,index_r,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating_r,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,0,5357bcf2bb72c5504882e889,2,120000,60000.0,4.219,320031.0,9.0,20.0,54.0,54.0,8836.0,1.0,50.0,1018,Femmes dentelle manches courtes hauts hauts ch...,Women Lace Short Sleeve Long Tops Blouse Shirt...,7.0,22,EUR,100000,1,3.82,11913,5355.0,2430.0,1974.0,960.0,1194.0,0,0,0,0,"blouse,Fashion,Shirt,boho,Tops,summer t-shirts...",NaN,S,50,Livraison standard,2,0,46,50,NaN,NaN,CN,ApparelHeaven,primesalecolimited,"90 % avis positifs (320,031 notes)",320031,4.218866,5357bcf2bb72c5504882e889,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/567cb0925ff12c4829f07dfb,https://contestimg.wish.com/api/webimage/567cb...,567cb0925ff12c4829f07dfb,summer,2020-08
1,0,5357bcf2bb72c5504882e889,2,120000,60000.0,4.219,320031.0,9.0,20.0,54.0,54.0,8836.0,1.0,50.0,1534,Femmes Chemisier d'été Chemise Sexy Floral Che...,Womens Summer Blouse Sexy Floral Shirt Loose K...,11.0,18,EUR,20000,1,4.14,5759,3125.0,1205.0,838.0,305.0,286.0,0,0,0,0,"blouse,Summer,Fashion,Tops,kimono,Casual,Jacke...",pink,S,50,Livraison standard,3,0,46,50,1.0,Quantité limitée !,CN,ApparelHeaven,primesalecolimited,"90 % avis positifs (320,031 notes)",320031,4.218866,5357bcf2bb72c5504882e889,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/572981a997dc5f5d3c5f0651,https://contestimg.wish.com/api/webimage/57298...,572981a997dc5f5d3c5f0651,summer,2020-08

3. Algunas de las columnas tienen `.` en sus nombres y en otras tenemos `_`.  Unifica el nombre de las columnas para que todas tengan "_". Además, todas deben estar en minúsculas.

In [174]:
nombres_columnas = [column.replace('.', '_').lower() for column in df_mer.columns]
df_mer.columns = nombres_columnas
df_mer.head(1)

,index,merchant_id,listed_products,total_units_sold,mean_units_sold_per_product,rating,merchant_ratings_count,mean_product_prices,mean_retail_prices,average_discount,mean_discount,mean_product_ratings_count,total_urgency_count,urgency_text_rate,index_r,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating_r,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,0,5357bcf2bb72c5504882e889,2,120000,60000.0,4.219,320031.0,9.0,20.0,54.0,54.0,8836.0,1.0,50.0,1018,Femmes dentelle manches courtes hauts hauts ch...,Women Lace Short Sleeve Long Tops Blouse Shirt...,7.0,22,EUR,100000,1,3.82,11913,5355.0,2430.0,1974.0,960.0,1194.0,0,0,0,0,"blouse,Fashion,Shirt,boho,Tops,summer t-shirts...",NaN,S,50,Livraison standard,2,0,46,50,NaN,NaN,CN,ApparelHeaven,primesalecolimited,"90 % avis positifs (320,031 notes)",320031,4.218866,5357bcf2bb72c5504882e889,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/567cb0925ff12c4829f07dfb,https://contestimg.wish.com/api/webimage/567cb...,567cb0925ff12c4829f07dfb,summer,2020-08

2. Explorad el nombre de las columnas, ¿hay alguna que este repetida o que no nos aporte información de valor? ¿Hay alguna columna que solo tenga un valor? En caso de ser así, eliminadlas. **NOTA** Hay tres columnas que cuando exploramos sus valores únicos y sus frecuencias ayer, nos deberíamos haber dado cuenta que solo tiene un valor.

In [175]:
df_mer.shape

(1573, 58)

In [176]:
df_mer.columns.nunique()

57

In [177]:
valores_unicos =df_mer.nunique()
valores_unicos

index                            958
merchant_id                      958
listed_products                   11
total_units_sold                 108
mean_units_sold_per_product      103
rating                           552
merchant_ratings_count           917
mean_product_prices              193
mean_retail_prices               190
average_discount                 112
mean_discount                    215
mean_product_ratings_count       596
total_urgency_count                6
urgency_text_rate                 13
index_r                         1573
title                           1201
title_orig                      1203
price                            127
retail_price                     104
currency_buyer                     1
units_sold                        15
uses_ad_boosts                     2
rating_r                         192
rating_count                     761
rating_five_count                605
rating_four_count                440
rating_three_count               384
rating_two_count                 262
rating_one_count                 330
badges_count                       4
badge_local_product                2
badge_product_quality              2
badge_fast_shipping                2
tags                            1230
product_color                    101
product_variation_size_id        106
product_variation_inventory       48
shipping_option_name              15
shipping_option_price              8
shipping_is_express                2
countries_shipped_to              94
inventory_total                   10
has_urgency_banner                 1
urgency_text                       2
origin_country                     6
merchant_title                   958
merchant_name                    957
merchant_info_subtitle          1058
merchant_rating_count            917
merchant_rating                  952
merchant_id                      958
merchant_has_profile_picture       2
merchant_profile_picture         125
product_url                     1341
product_picture                 1341
product_id                      1341
theme                              1
crawl_month                        1
dtype: int64

In [178]:
columnas_un_valor = valores_unicos[valores_unicos == 1].index.tolist() # .index obtiene el índice de la Serie filtrada, que corresponde a los nombres de las columnas con un solo valor único. tolist() convierte este índice (que es un objeto de pandas) en una lista de Python. Esto es útil porque muchos métodos de pandas y Python aceptan listas como argumentos. 
columnas_un_valor

['currency_buyer', 'has_urgency_banner', 'theme', 'crawl_month']

In [179]:
df_mer = df_mer.drop(columns=columnas_un_valor)
df_mer.head(1)

,index,merchant_id,listed_products,total_units_sold,mean_units_sold_per_product,rating,merchant_ratings_count,mean_product_prices,mean_retail_prices,average_discount,mean_discount,mean_product_ratings_count,total_urgency_count,urgency_text_rate,index_r,title,title_orig,price,retail_price,units_sold,uses_ad_boosts,rating_r,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id
0,0,5357bcf2bb72c5504882e889,2,120000,60000.0,4.219,320031.0,9.0,20.0,54.0,54.0,8836.0,1.0,50.0,1018,Femmes dentelle manches courtes hauts hauts ch...,Women Lace Short Sleeve Long Tops Blouse Shirt...,7.0,22,100000,1,3.82,11913,5355.0,2430.0,1974.0,960.0,1194.0,0,0,0,0,"blouse,Fashion,Shirt,boho,Tops,summer t-shirts...",NaN,S,50,Livraison standard,2,0,46,50,NaN,CN,ApparelHeaven,primesalecolimited,"90 % avis positifs (320,031 notes)",320031,4.218866,5357bcf2bb72c5504882e889,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/567cb0925ff12c4829f07dfb,https://contestimg.wish.com/api/webimage/567cb...,567cb0925ff12c4829f07dfb

In [180]:
df_mer.shape

(1573, 54)

4. En la columna de `merchant_info_subtitle`, si nos fijamos hay algunas celdas donde tenemos entre paréntesis el número total de calificaciones para el comerciante (que es la misma información que la que tenemos en la columna "merchant_rating_count"). Eliminad de la columna "merchant_info_subtitle" la parte del *string* de los paréntesis. Guardar el resultado de vuestra limpieza en una columna que se llame igual, es decir, "merchant_info_subtitle".

In [181]:
df_mer[['merchant_info_subtitle']].head()

               merchant_info_subtitle
0  90 % avis positifs (320,031 notes)
1  90 % avis positifs (320,031 notes)
2  84 % avis positifs (139,223 notes)
3  84 % avis positifs (139,223 notes)
4  84 % avis positifs (139,223 notes)

Uso Regex para eliminar contenido entre parentesis:

In [182]:
df_mer['merchant_info_subtitle'] = df_mer['merchant_info_subtitle'].str.replace(r'\s*\(.*?\)\s*', '', regex=True)
df_mer[['merchant_info_subtitle']].head()

  merchant_info_subtitle
0     90 % avis positifs
1     90 % avis positifs
2     84 % avis positifs
3     84 % avis positifs
4     84 % avis positifs

5. Si nos fijamos, en la primera fila antes solo teníamos un paréntesis, pero los hemos eliminado en el paso anterior, y ahora tenemos un *string* vacío, lo cual no tiene mucho sentido. En este ejercicio debereis reemplazar esos *strings* vacios por nulos de Pandas (**NOTA** estos deben ser indicados de la siguiente forma `np.nan`, y deberéis importar numpy).

Veo cuantas filas vacias/no nulas existen en la columna:

In [183]:
filas_vacias = df_mer[(df_mer['merchant_info_subtitle'] == '') & (df_mer['merchant_info_subtitle'].notna())]
filas_vacias.shape

(293, 54)

Reemplazo strings vacios por valores nulos:

In [184]:
df_mer['merchant_info_subtitle'] = df_mer['merchant_info_subtitle'].replace('', np.nan)

In [201]:
df_mer[['merchant_info_subtitle']].sample()

     merchant_info_subtitle
1558                    NaN

6. Hay ciertas columnas que no vamos a necesitar para nuestro análisis. En concreto, vamos a eliminar las columnas de `badges_count`, `product_variation_inventory`, `urgency_text`, `merchant_title`, `merchant_has_profile_picture`, `merchant_profile_picture`, `product_picture`, `total_urgency_count`, `has_urgency_banner` y `urgency_text_rate`. Guardad los cambios realizados hasta este punto en un csv para usarlo en los ejercicios de la lección de mañana.

In [186]:
df_mer.columns

Index(['index', 'merchant_id', 'listed_products', 'total_units_sold',
       'mean_units_sold_per_product', 'rating', 'merchant_ratings_count',
       'mean_product_prices', 'mean_retail_prices', 'average_discount',
       'mean_discount', 'mean_product_ratings_count', 'total_urgency_count',
       'urgency_text_rate', 'index_r', 'title', 'title_orig', 'price',
       'retail_price', 'units_sold', 'uses_ad_boosts', 'rating_r',
       'rating_count', 'rating_five_count', 'rating_four_count',
       'rating_three_count', 'rating_two_count', 'rating_one_count',
       'badges_count', 'badge_local_product', 'badge_product_quality',
       'badge_fast_shipping', 'tags', 'product_color',
       'product_variation_size_id', 'product_variation_inventory',
       'shipping_option_name', 'shipping_option_price', 'shipping_is_express',
       'countries_shipped_to', 'inventory_total', 'urgency_text',
       'origin_country', 'merchant_title', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'merchant_has_profile_picture',
       'merchant_profile_picture', 'product_url', 'product_picture',
       'product_id'],
      dtype='object')

Columna 'has_urgency_banner' no existe en el DataFrame, porque la he borrado cuando eliminé columnas con valores únicos.

In [187]:
df_mer.shape

(1573, 54)

In [213]:
columnas_eliminar = [
    'badges_count', 'product_variation_inventory', 'urgency_text',
    'merchant_title', 'merchant_has_profile_picture','product_picture', 
    'total_urgency_count', 'urgency_text_rate']

df_mer = df_mer.drop(columns=columnas_eliminar)

Verifico que se han borrado 8 columnas:

In [214]:
df_mer.shape

(1573, 46)

In [236]:
df_final = df_mer.to_csv('df-rating-insight-leccion-04.csv')

7. Pongamos en práctica el filtrado de datos en Pandas: 

    - Seleccionad aquellos productos cuyo color es verde. ¿Cuántos productos tenemos?

    - Seleccionad aquellos productos cuyo color es verde y rojo. ¿Cuántos productos tenemos de cada tipo de color?

    - Seleccionad aquellos productos de la talla M, que valgan más de 15. ¿Cuántos productos tenemos?

    - Seleccionad aquellos productos cuyo precio este entre 1 y 2 (ambos inclusive). ¿Cuántos productos tenemos?

    - Filtrad los datos, para extraer solo aquellos productos que tengan uno o más dígitos en su titulo. ¿Cuántos productos hay?

Convierto los valores de la columna a minusculas para evitar errores:

In [223]:
df_mer['product_color'] = df_mer['product_color'].str.lower()

In [248]:
productos_verdes = df_mer[df_mer['product_color'] == 'green']
cantidad_productos_verdes = productos_verdes.shape[0] # Uso .shape[0]para contar el número de filas en el DataFrame productos_verdes

print(f'la cantidad de productos color verde  es:\n {cantidad_productos_verdes}')

la cantidad de productos color verde  es:
 90

Usamos .isin() porque son varios valores:

In [249]:
productos_vr = df_mer[df_mer['product_color'].isin(['green', 'red'])]
cantidad_productos_vr = productos_vr.shape[0]
print(f'la cantidad de productos color verde y rojo es:\n {cantidad_productos_vr}')

la cantidad de productos color verde y rojo es:
 184

Busco que columnas pueden tener el valor 'M':

In [235]:
columnas_con_m = []
for columna in df_mer.columns:
    try:
        if df_mer[columna].astype(str).str.contains('M').any():
            columnas_con_m.append(columna)
    except AttributeError:
        # cuando la columna no puede ser convertida a string.
        continue

print(f"Columnas con 'M': {columnas_con_m}")

Columnas con 'M': ['title', 'title_orig', 'tags', 'product_variation_size_id']

Uso 'product_variation_size_id':

In [241]:
productos_m15 = df_mer[(df_mer['product_variation_size_id'] == 'M') & (df_mer['price'] > 15)]
productos_m15.sample(2)

,index,merchant_id,listed_products,total_units_sold,mean_units_sold_per_product,rating,merchant_ratings_count,mean_product_prices,mean_retail_prices,average_discount,mean_discount,mean_product_ratings_count,index_r,title,title_orig,price,retail_price,units_sold,uses_ad_boosts,rating_r,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,origin_country,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_profile_picture,product_url,product_id
1417,822,595097d6a26f6e070cb878d1,1,100,100.0,4.129,568.0,16.0,14.0,-14.0,-14.0,54.0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0,0,0,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,4,0,34,50,CN,zgrdejia,NaN,568,4.128521,595097d6a26f6e070cb878d1,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,5e9ae51d43d6a96e303acdb0
1306,711,5dc818ca030a154e48a3a8af,1,100,100.0,3.367,572.0,16.0,14.0,-14.0,-14.0,27.0,1284,Séchage rapide 2 pièces ensemble homme décontr...,Quick Dry 2 Pieces Set Casual Man Clothes Summ...,16.0,14,100,1,3.44,27,13.0,2.0,2.0,4.0,6.0,0,0,0,"mensummertshirt,Summer,Fashion,Men's Fashion,S...",black,M,Livraison standard,4,0,35,50,VE,hernadezyeli,70 % avis positifs,572,3.367133,5dc818ca030a154e48a3a8af,NaN,https://www.wish.com/c/5eba38a9d0c9a464e4490d20,5eba38a9d0c9a464e4490d20

In [245]:
cantidad_m15 = productos_m15.shape[0]
print(f'la cantidad de productos talla "M" de precio mayor a 15 es:\n {cantidad_m15}')

la cantidad de productos talla "M" de precio mayor a 15 es:
 17

In [244]:
precio_1_2 = df_mer[(df_mer['price'] >= 1) & (df_mer['price'] <= 2)]
cantidad_precio_1_2 = precio_1_2.shape[0]
print(f' La cantidad de productos con precio entre 1-2 es: \n {cantidad_precio_1_2}')

 La cantidad de productos con precio entre 1-2 es:
 77

Uso Regex para seleccionar titulos que contengan digitos:

In [254]:
productos_con_digitos = df_mer[df_mer['title'].str.contains(r'\d')]
productos_con_digitos['title'].head()

0     Femmes dentelle manches courtes hauts hauts ch...
2     2018 New Fashion Women's Tops Sexy Strappy Sle...
5     Femme 2019 nouvelle mode sexe débardeurs été d...
11    Femmes Camisole extensible Spaghetti Strap Lon...
12    2019 Summer Women's Fashion Nouvelle robe sans...
Name: title, dtype: object

NOTA: Como no muestra la informacion completa he verificado en el .csv original que estos primeros 5 titulos contienen digitos.

In [255]:
cantidad_productos_con_digitos = productos_con_digitos.shape[0]
print(f'La cantidad de titulos que contienen digitos es: \n {cantidad_productos_con_digitos}')

La cantidad de titulos que contienen digitos es:
 579